# Save as: openapi.yml
openapi: 3.0.0
info:
  title: Test API for HelioVerify
  version: 1.0.0

paths:
  /users:
    get:
      tags:
        - UserService  # Your parser will group this under 'UserService'
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: A list of users.
          
    post:
      tags:
        - UserService
      summary: Create a new user
      operationId: createUser # Your parser will see POST and mark this for auth
      responses:
        '201':
          description: User created.

  /users/{id}:
    get:
      tags:
        - UserService
      summary: Get a single user by ID
      operationId: getUserById # This route will be missing from the code
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single user.

  /auth/login:
    post:
      tags:
        - AuthService # Your parser will group this under 'AuthService'
      summary: Log in a user
      operationId: loginUser
      responses:
        '200':
          description: Auth token.